2023-04-02 13:40:45,594 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 13:43:46,529 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 13:43:52,574 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 15:52:13,453 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 15:57:31,572 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 21:25:38,389 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 21:25:52,513 ERROR: Exception on /user/susan [GET] [in /Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/emalkhan/microblog/app/routes.py", line 84, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/emalkhan/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/emalkhan/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/emalkhan/microblog/app/templates/user.html", line 16, in block 'content'
    <form action="{{ url_for('follow', username=user.username) }}" method="post">
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2023-04-02 21:27:09,814 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
2023-04-02 21:27:20,227 ERROR: Exception on /user/susan [GET] [in /Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/emalkhan/microblog/app/routes.py", line 84, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/emalkhan/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/emalkhan/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/emalkhan/microblog/app/templates/user.html", line 16, in block 'content'
    <form action="{{ url_for('follow', username=user.username) }}" method="post">
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2023-04-02 21:27:39,127 ERROR: Exception on /user/susan [GET] [in /Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py:1744]
Traceback (most recent call last):
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/emalkhan/microblog/app/routes.py", line 84, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/emalkhan/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/emalkhan/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/emalkhan/microblog/app/templates/user.html", line 16, in block 'content'
    <form action="{{ url_for('follow', username=user.username) }}" method="post">
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/emalkhan/microblog/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'follow' with values ['username']. Did you mean 'login' instead?
2023-04-02 21:35:38,867 INFO: Microblog startup [in /Users/emalkhan/microblog/app/__init__.py:45]
